name: CI Build and Test

on:
  push:
    branches: [ main, develop ]
  pull_request:
    branches: [ main ]

jobs:
  build-linux:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v3
    
    - name: Install dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y build-essential flex bison
    
    - name: Build
      run: make
    
    - name: Test
      run: |
        ./jqlite '.' test.json
        ./jqlite '.name' test.json
        ./jqlite '.posts[0].title' test.json
        ./jqlite '.settings.theme' test.json
    
    - name: Upload artifact
      uses: actions/upload-artifact@v3
      with:
        name: jqlite-linux
        path: jqlite

  build-macos:
    runs-on: macos-latest
    
    steps:
    - uses: actions/checkout@v3
    
    - name: Install dependencies
      run: |
        brew install flex bison
    
    - name: Build
      run: make
    
    - name: Test
      run: |
        ./jqlite '.' test.json
        ./jqlite '.name' test.json
        ./jqlite '.posts[0].title' test.json
    
    - name: Upload artifact
      uses: actions/upload-artifact@v3
      with:
        name: jqlite-macos
        path: jqlite

  build-windows:
    runs-on: windows-latest
    
    steps:
    - uses: actions/checkout@v3
    
    - name: Setup MSYS2
      uses: msys2/setup-msys2@v2
      with:
        msystem: MINGW64
        update: true
        install: >-
          mingw-w64-x86_64-gcc
          flex
          bison
          make
    
    - name: Build
      shell: msys2 {0}
      run: make
    
    - name: Test
      shell: msys2 {0}
      run: |
        ./jqlite.exe '.' test.json
        ./jqlite.exe '.name' test.json
        ./jqlite.exe '.posts[0].title' test.json
    
    - name: Upload artifact
      uses: actions/upload-artifact@v3
      with:
        name: jqlite-windows
        path: jqlite.exe
